---
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: enmasse
    name: authservice
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: enmasse
          name: authservice
      spec:
        containers:
        - env:
          - name: LISTENPORT
            value: '56672'
          image: docker.io/enmasseproject/none-authservice:latest
          livenessProbe:
            tcpSocket:
              port: amqp-auth
          name: none-authservice
          ports:
          - containerPort: 56672
            name: amqp-auth
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 64Mi
        - image: docker.io/enmasseproject/keycloak-authservice:latest
          livenessProbe:
            tcpSocket:
              port: amqp-keycloak
          name: keycloak
          ports:
          - containerPort: 5677
            name: amqp-keycloak
          - containerPort: 8080
            name: http-keycloak
          volumeMounts:
          - mountPath: "/var/run/keycloak"
            name: keycloak-secret
            readOnly: true
          - mountPath: "/opt/jboss/keycloak/standalone/data"
            name: keycloak-persistence
        volumes:
        - name: keycloak-secret
          secret:
            secretName: keycloak-credentials
        - emptyDir: {}
          name: keycloak-persistence
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: none-authservice
  spec:
    ports:
    - name: amqp-auth
      port: 5672
      protocol: TCP
      targetPort: amqp-auth
    selector:
      name: authservice
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: standard-authservice
  spec:
    ports:
    - name: amqp-auth
      port: 5672
      protocol: TCP
      targetPort: amqp-keycloak
    - name: http-keycloak
      port: 8080
      protocol: TCP
      targetPort: http-keycloak
    selector:
      name: authservice
kind: List
