---
apiVersion: v1
kind: Template
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: enmasse
    name: keycloak
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: enmasse
          name: keycloak
      spec:
        containers:
        - image: "${standard_authservice_IMAGE}"
          livenessProbe:
            tcpSocket:
              port: amqp
          name: keycloak
          ports:
          - containerPort: 5677
            name: amqp
          - containerPort: 8080
            name: http
          volumeMounts:
          - mountPath: "/var/run/keycloak"
            name: keycloak-secret
            readOnly: true
          - mountPath: "/opt/jboss/keycloak/standalone/data"
            name: keycloak-persistence
        volumes:
        - name: keycloak-secret
          secret:
            secretName: "${KEYCLOAK_SECRET_NAME}"
        - emptyDir: {}
          name: keycloak-persistence
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: standard-authservice
  spec:
    ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: amqp
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      name: keycloak
parameters:
- description: The docker image to use for the 'standard' auth service
  name: standard_authservice_IMAGE
  value: docker.io/enmasseproject/keycloak:latest
- description: The secret where keycloak credentials are stored
  name: KEYCLOAK_SECRET_NAME
  value: keycloak-credentials
